version: '3'
services:
  yolo:
    build: .
    image: yolo:latest
    container_name: yolo
    volumes:
      - ./cfg:/yolo/cfg
      - ./data:/yolo/data
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://<musera11>:<nWtKNkuX70oVFfMJ>@cluster1.ykhmd7r.mongodb.net/?retryWrites=true&w=majority
    command: ["npm", "start"]
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    networks:
        - yolo_network
    ports:
      - "27017:27017"
networks:
    yolo_network:
      driver: bridge