version: '3'

services:
  client:
     container_name: yoloclient
     build: ./client
     ports: 
       - "3000:3000"
     stdin_open: true
     depends_on:
       - backend
     networks:
       - yolo-network 
  backend:
     container_name: yolobackend
     build: ./backend
     environment:
       - MONGODB_URI=mongodb://yolomongodb:27017
     ports: 
       - "5000:5000"
     depends_on:
       - database
     networks: 
       - yolonetwork
  database:
     image: mongo:latest
     container_name: yolomongodb
     ports:
      - "27017:27017"
     networks:
      - yolonetwork
     volumes: 
      - ./data:/data/db
networks:
  yolo-network:
    name: yolonetwork
    driver: bridge
