version: '3'
services:
  yolo:
    build: .
    image: yolo:latest
    container_name: yolo
    volumes:
      - ./cfg:/yolo/cfg
      - ./data:/yolo/data
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yolo
    command: ["npm", "start"]
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
